= Busy Java Developer’s Hand-on of DDD with Apache Isis

This repository holds the slides for the
link:http://ncrafts.io/speaker/dkhaywood#nc18-dha01[Busy Java Developer’s Hand-on of DDD with Apache Isis] session, run at
link:https://ncrafts.io/[NCrafts 2018].


Being presented by link:http://ncrafts.io/speaker/dkhaywood[Dan Haywood] .




== Under the covers

The slides have been developed using link:http://asciidoctor.org/[AsciiDoctor], using
link:http://lab.hakim.se/reveal-js/[reveal.js] as the rendering backend.



== To build and preview

To build and preview the website, use:

[source,bash]
----
$ sh preview.sh
----

or in long-hand:

[source,bash]
----
./gradlew --offline asciidoctor &&  python -m webbrowser -t http://localhost:4000  && pushd build/asciidoc/revealjs && python -m http.server 4000 && popd
----

This will open up the web browser at link:http://localhost:4000/index.html[]



== To publish

The slides is hosted at link:http://danhaywood.github.io/jaxlondon2016[danhaywood.github.io/jaxlondon2016], using github's
`gh-pages`.  A CNAME record redirects to link:http://danhaywood.com/jaxlondon2016[Dan's blog].

Assuming that a second copy of the repository is checked out to `../jaxlondon2016-gh-pages`, in the `gh-pages` branch, use:

[source,bash]
----
sh publish.sh
----

or in long-hand:

[source,bash]
----
pushd ../jaxlondon2016-gh-pages
git rm -rf .
popd
pushd build/asciidoc/revealjs
cp -r . ../../../../jaxlondon2016-gh-pages/.
popd
pushd ../jaxlondon2016-gh-pages
git add .
git commit -m "updating"
git push origin gh-pages
popd
----




== Appendices

=== Preparing the `gh-pages` branch

Using the procedure described https://help.github.com/articles/creating-project-pages-manually/[here], the
following steps were performed to set up the `gh-pages` branch for publishing:

[source,bash]
----
git clone https://github.com/danhaywood/jaxlondon2016.git ../jaxlondon2016-gh-pages
cd ../jaxlondon2016-gh-pages
git checkout --orphan gh-pages
git rm -rf .
rm '.gitignore'
echo "My Page" > index.html
git add index.html
git commit -a -m "First pages commit"
git push origin gh-pages
----


=== IntelliJ

If you're using IntelliJ you can generate the IDE's files via:

 $ ./gradlew idea

Open the file _build/asciidoc/reveal/example-manual.html_ in your browser to see the generated revealjs file.
